### ISSUE TITLE
Delete Split leaves split amounts in budget 

### ISSUE THREAD

**Issue by kazzazed** [actualbudget/releases#114]
Steps to recreate:
1. Enter a split transaction to on budget account. Split over 2 or more categories. Assign budget to categories.
2. Delete split transaction by selecting on main line and D.
3. Review budget - the transactions still show in the Spent column. Clicking on the spent amount opens category for the month shows "no transactions" (or if there were other transactions in the category, the split amount is not shown)
4. Although the deleted amount shows in the Spent column, the total is not included in the month summary at top of screen.
To fix:
Reset budget cache.
To avoid:
work-around to avoid is when deleting the split transaction to first delete the split lines, then the main line. 

Also noted that if you add new transactions to the same category it also corrects the issue, possibly this action causes a re-calc of the category amount.

**Comment by AlexioXela** [comment]
This must be what happened to me. I'm currently running Actual and YNAB together, but they showed different amounts "available" in YNAB or "Balance" in Actual. After spending a lot of time tracking down the difference, it turns out that two categories in Actual were miscalculating the spent amount. They were miscalculating it by the amount of a split transaction that had previously been duplicated somehow, so I deleted the duplicate. Due to this bug, the deleted transaction still counted as spent though.

I'm not sure what 4. above "total is not included in the month summary at top of screen" means, but for me I believe this was impacting my "overbudgeted" amount, "Spent" total for the month, and "Balance" remaining for the month. Resetting the budget cache did the trick, thanks!
