### ISSUE TITLE
"Hold for next month" does not update the next month's available funds

### ISSUE THREAD

**Issue by calebperkins** [actualbudget/releases#150]
I am in December 2021 and I have $X funds to budget; I want to hold $Y for January 2022. If I click on December and select hold for next month,  the available funds / To budget for January 2022 does not increase.

Here is a screen recording; as you can see the next month's available funds does not update. If I select "hold $100 for January", and then try to budget $100 in a category for January, Actual says I have over spent the category for January even though I held funds for that month.

https://user-images.githubusercontent.com/300328/146158806-ec1f12fd-73dd-47be-97f7-72236d1b0a77.mov

**Comment by bpaulien** [comment]
You're looking in the wrong place.  The total available funds doesn't (and shouldn't) change.  Look in the December header, just above your To Budget: (where it says "For Next Month".  That amount goes up, and the amount available "To Budget" goes down by that amount.  This indicates that you no longer have that amount this month to budget, but are saving some of it for next month.  The TOTAL amount Available  in January hasn't changed.  But the amount available for you to budget in December has gone down.

Since you have already budgeted money in January, and moved the remainder over to next month (notice the 482.66 in January's header "For Next Month".)  All the money is accounted for.  If you move over to February, you should see that there's 482.66 available there.  If you no longer wish to hold that for Feb, you can clear that out, and it will be available in January.

**Comment by bpaulien** [comment]
To continue my thought, If you budget anything new into December, you'll see that the "To Budget" in January will go negative.  That's because you've already accounted for that money in January.  So, if you're done with your December budget, just move all of it over to January so it doesn't look like it's still available for you in December.

**Comment by calebperkins** [comment]
Oh gotcha! I think I accidentally moved money into February (I normally just budget one month ahead), so I was confused why I couldn't budget more in January. I also didn't understand the distinction between budgeting money in a future month with or without "holding the money for next month" so I was a little confused how the available funds work.

Thank you for the help.
